[[redirects]]
  from = "https://book.loanpros.io/*"
  to = "/book.html"
  status = 200
  force = true

[[redirects]]
  from = "https://start.loanpros.io/*"
  to = "/start.html"
  status = 200
  force = true

[[redirects]]
  from = "https://thanks.loanpros.io/*"
  to = "/thanks.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
