[[redirects]]
  from = "https://book.loanpros.io/*"
  to = "/book"
  status = 200
  force = true

[[redirects]]
  from = "https://start.loanpros.io/*"
  to = "/start"
  status = 200
  force = true

[[redirects]]
  from = "https://thanks.loanpros.io/*"
  to = "/thanks"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
